/**
 * SonicWALL Security Appliance API
 * SonicWALL Security Appliance API
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

'use strict';
import * as models from './models';

export interface ModelInterface {
    

    /**
     * Unique identifier representing an interfae.
     */
    uuid?: string;

    /**
     * Interface name.
     */
    name?: string;

    /**
     * 0 - MGMT, 1 - DPDK Interface, 2 - Other
     */
    type?: number;

    /**
     * all IPv4 addresses that belong to the interface
     */
    ipv4?: Array<models.Ipv4Address>;

    /**
     * all IPv6 addresses that belong to the interface
     */
    ipv6?: Array<models.Ipv6Address>;

    /**
     * uuid of paired interface,  blank if the interface doesn't have a pair 
     */
    pair?: string;
}
